{
 "title": "PromoTrack API Monitoring",
 "time": { "from": "2026-05-12T19:28:46.479Z", "to": "2026-05-12T23:22:52.047Z" },
 "panels": [
  { "title": "Estado general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"promotrack-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"promotrack-api\", uri!~\"/actuator.*\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"promotrack-api\", uri!~\"/actuator.*\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"promotrack-api\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tráfico HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Requests by HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (status) (\r\n  rate(http_server_requests_seconds_count{job=\"promotrack-api\", uri!~\"/actuator.*\"}[5m])\r\n) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (method, uri) (\r\n  rate(http_server_requests_seconds_count{job=\"promotrack-api\", uri!~\"/actuator.*\"}[5m])\r\n) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "HTTP 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"promotrack-api\", status=~\"5..\", uri!~\"/actuator.*\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"promotrack-api\", status=~\"4..\", uri!~\"/actuator.*\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runtime JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"promotrack-api\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}