spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/promotrack}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:promotrack}
    password: ${SPRING_DATASOURCE_PASSWORD:promotrack}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-postgres.sql

logging:
  level:
    org.hibernate.SQL: debug
