spring:
  application:
    name: promotrack-api
  profiles:
    active: dev

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: PromoTrack API
    description: API REST para gestionar ofertas de supermercados argentinos
    version: 1.1.0
